# This configuration file is used internally
# to fill default settings for on-prem Ray clusters
# bootstrapped by the Ray autoscaler.
# For annotated examples, see the example yamls in this directory.

cluster_name: default

auth: {}

upscaling_speed: 1.0
idle_timeout_minutes: 5

docker: {}
provider:
  type: local
  head_ip: YOUR_HEAD_NODE_HOSTNAME
    # You may need to supply a public ip for the head node if you need
    # to run `ray up` from outside of the Ray cluster's network
    # (e.g. the cluster is in an AWS VPC and you're starting ray from your laptop)
    # This is useful when debugging the local node provider with cloud VMs.
    # external_head_ip: YOUR_HEAD_PUBLIC_IP
  worker_ips: [ WORKER_NODE_1_HOSTNAME, WORKER_NODE_2_HOSTNAME, ... ]

# Defaults are empty to avoid any surprise changes to on-prem cluster's state.
# Refer to example yamls for examples of ray installation in setup commands.
initialization_commands: []
setup_commands: []
head_setup_commands: []
worker_setup_commands: []

head_start_ray_commands:
  - ray stop
  - ulimit -c unlimited; ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
  - ray stop
  - ray start --address=$RAY_HEAD_IP:6379

file_mounts: {}
cluster_synced_files: []
file_mounts_sync_continuously: false
rsync_exclude: []
rsync_filter: []
